#!/usr/bin/zsh
emulate -L zsh
setopt ERR_EXIT NO_UNSET PIPE_FAIL

typeset -r package_root=${0:A:h}
typeset -r source_archive=${1:-${package_root}/open_webui-0.11.0.tar.gz}
typeset -r output_path=${2:-${package_root}/open-webui-private-requirements.lock}
typeset -r expected_source_sha256=e28c4fa997bf0a678caa7a0db6441da2e0c33b9a4120677f959ec3e45fccf9e9
typeset -r expected_uv_version='uv 0.12.5 (210d1f678 2026-08-14 x86_64-unknown-linux-gnu)'
typeset -r uv_lock_member=open_webui-0.11.0/uv.lock

if [[ ! -f ${source_archive} ]]; then
  print -u2 -- "source archive is unavailable: ${source_archive}"
  exit 2
fi

typeset source_sha256
source_sha256=$(/usr/bin/sha256sum -- "${source_archive}")
source_sha256=${source_sha256%% *}
if [[ ${source_sha256} != ${expected_source_sha256} ]]; then
  print -u2 -- "source archive SHA-256 is ${source_sha256}; expected ${expected_source_sha256}"
  exit 2
fi

typeset uv_version
uv_version=$(/usr/bin/uv --version)
if [[ ${uv_version} != ${expected_uv_version} ]]; then
  print -u2 -- "uv version is ${uv_version}; expected ${expected_uv_version}"
  exit 2
fi

typeset work_root
work_root=$(/usr/bin/mktemp -d /tmp/open-webui-private-lock.XXXXXX)
trap '/usr/bin/rm -rf -- "${work_root}"' EXIT HUP INT TERM
/usr/bin/install -d "${work_root}/home"

/usr/bin/bsdtar -xOf "${source_archive}" "${uv_lock_member}" > "${work_root}/uv.lock"

typeset -a clean_environment
clean_environment=(
  "HOME=${work_root}/home"
  'PATH=/usr/bin'
)
typeset environment_name
for environment_name in \
  HTTP_PROXY HTTPS_PROXY ALL_PROXY NO_PROXY \
  http_proxy https_proxy all_proxy no_proxy \
  SSL_CERT_FILE SSL_CERT_DIR; do
  if (( ${+parameters[${environment_name}]} )); then
    clean_environment+=("${environment_name}=${(P)environment_name}")
  fi
done

/usr/bin/env -i "${clean_environment[@]}" /usr/bin/uv pip compile \
  "${package_root}/open-webui-private-constraints.txt" \
  --python /usr/bin/python3.14 \
  --python-platform x86_64-unknown-linux-gnu \
  --excludes "${package_root}/open-webui-system-providers.txt" \
  --default-index https://pypi.org/simple \
  --generate-hashes \
  --no-header \
  --no-annotate \
  --exclude-newer 2026-08-18T06:25:20Z \
  --cache-dir "${UV_CACHE_DIR:-${work_root}/uv-cache}" \
  --no-config \
  --quiet \
  --output-file "${work_root}/requirements.body"

{
  print -r -- '# Generated by generate-open-webui-private-lock.zsh; do not edit.'
  print -r -- '# Open WebUI 0.11.0 uv.lock SHA-256: bf42de5c836d5afe5628533cf8369e856d5d09bfd00efef302c31df3fa249947'
  print -r -- '# Target: CPython 3.14 on x86_64-unknown-linux-gnu; uv 0.12.5.'
  print -r -- '# Graph: base release closure plus optional qdrant-client, excluding system providers.'
  print -r -- '# Index cutoff: 2026-08-18T06:25:20Z.'
  /usr/bin/cat -- "${work_root}/requirements.body"
} > "${work_root}/requirements.lock"

/usr/bin/python3.14 "${package_root}/verify-open-webui-private-lock.py" \
  "${work_root}/uv.lock" \
  "${package_root}/open-webui-private-constraints.txt" \
  "${package_root}/open-webui-system-providers.txt" \
  "${work_root}/requirements.lock"

/usr/bin/install -Dm644 "${work_root}/requirements.lock" "${output_path}"
/usr/bin/sha256sum -- "${output_path}"
