#!/usr/bin/python3
"""Verify the exact Open WebUI private-closure derivation contract."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from collections import defaultdict, deque
from pathlib import Path

import tomllib
from packaging.markers import InvalidMarker, Marker

EXPECTED_UV_LOCK_SHA256 = (
    "bf42de5c836d5afe5628533cf8369e856d5d09bfd00efef302c31df3fa249947"
)
EXPECTED_RESOLUTION_MARKER = (
    "python_full_version >= '3.12' and sys_platform != 'emscripten' "
    "and sys_platform != 'win32'"
)
EXPECTED_EXTERNALIZED = (
    "accelerate",
    "av",
    "ctranslate2",
    "faster-whisper",
    "numpy",
    "onnxruntime",
    "opencv-python",
    "opencv-python-headless",
    "pandas",
    "pillow",
    "pyarrow",
    "pyclipper",
    "rapidocr",
    "scikit-learn",
    "scipy",
    "sentence-transformers",
    "sentencepiece",
    "shapely",
    "tokenizers",
    "torch",
    "transformers",
)
EXPECTED_QDRANT_CLOSURE = {
    "portalocker": "3.2.0",
    "qdrant-client": "1.18.0",
}
EXPECTED_HEADER = (
    "# Generated by generate-open-webui-private-lock.zsh; do not edit.",
    f"# Open WebUI 0.11.0 uv.lock SHA-256: {EXPECTED_UV_LOCK_SHA256}",
    "# Target: CPython 3.14 on x86_64-unknown-linux-gnu; uv 0.12.5.",
    "# Graph: base release closure plus optional qdrant-client, excluding system providers.",
    "# Index cutoff: 2026-08-18T06:25:20Z.",
)
REQUIREMENT_PATTERN = re.compile(
    r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^ \\]+)(?: \\)?$"
)
HASH_PATTERN = re.compile(r"^    --hash=sha256:([0-9a-f]{64})(?: \\)?$")


class VerificationError(RuntimeError):
    """An input no longer represents the exact selected closure."""


def canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).casefold()


def read_lines(path: Path) -> list[str]:
    try:
        return path.read_text(encoding="utf-8").splitlines()
    except OSError as error:
        raise VerificationError(f"cannot read {path}: {error}") from error


def parse_name_list(path: Path, *, expected_count: int) -> tuple[str, ...]:
    names = tuple(read_lines(path))
    if any(not name or canonical(name) != name for name in names):
        raise VerificationError(f"{path} contains a noncanonical package name")
    if names != tuple(sorted(set(names))):
        raise VerificationError(f"{path} must contain unique sorted package names")
    if len(names) != expected_count:
        raise VerificationError(
            f"{path} has {len(names)} names; expected {expected_count}"
        )
    return names


def parse_constraints(path: Path) -> dict[str, str]:
    requirements: dict[str, str] = {}
    raw_lines = read_lines(path)
    if raw_lines != sorted(set(raw_lines)):
        raise VerificationError(f"{path} must contain unique sorted requirements")
    for line in raw_lines:
        match = re.fullmatch(
            r"([A-Za-z0-9][A-Za-z0-9._-]*)==([^ ;\\]+)", line
        )
        if match is None:
            raise VerificationError(f"invalid exact requirement in {path}: {line!r}")
        name = canonical(match.group(1))
        if name != match.group(1):
            raise VerificationError(f"noncanonical requirement name in {path}: {line!r}")
        requirements[name] = match.group(2)
    if len(requirements) != 222:
        raise VerificationError(
            f"{path} has {len(requirements)} requirements; expected 222"
        )
    return requirements


def parse_hashed_requirements(path: Path) -> dict[str, str]:
    lines = read_lines(path)
    if tuple(lines[: len(EXPECTED_HEADER)]) != EXPECTED_HEADER:
        raise VerificationError(f"{path} has missing or stale provenance header")

    requirements: dict[str, str] = {}
    hashes: dict[str, set[str]] = {}
    current_name: str | None = None
    for line in lines[len(EXPECTED_HEADER) :]:
        requirement_match = REQUIREMENT_PATTERN.fullmatch(line)
        if requirement_match is not None:
            name = canonical(requirement_match.group(1))
            if name != requirement_match.group(1) or name in requirements:
                raise VerificationError(
                    f"{path} has duplicate or noncanonical requirement {line!r}"
                )
            requirements[name] = requirement_match.group(2)
            hashes[name] = set()
            current_name = name
            continue

        hash_match = HASH_PATTERN.fullmatch(line)
        if hash_match is not None and current_name is not None:
            digest = hash_match.group(1)
            if digest in hashes[current_name]:
                raise VerificationError(
                    f"{path} repeats a hash for {current_name}: {digest}"
                )
            hashes[current_name].add(digest)
            continue

        raise VerificationError(f"unexpected requirements syntax in {path}: {line!r}")

    missing_hashes = sorted(name for name, values in hashes.items() if not values)
    if missing_hashes:
        raise VerificationError(
            f"{path} has unhashed requirements: {', '.join(missing_hashes)}"
        )
    if list(requirements) != sorted(requirements):
        raise VerificationError(f"{path} requirements are not sorted")
    return requirements


def parse_uv_lock(path: Path) -> dict[str, object]:
    try:
        raw = path.read_bytes()
        lock = tomllib.loads(raw.decode("utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError) as error:
        raise VerificationError(f"cannot parse {path}: {error}") from error
    digest = hashlib.sha256(raw).hexdigest()
    if digest != EXPECTED_UV_LOCK_SHA256:
        raise VerificationError(
            f"{path} SHA-256 is {digest}; expected {EXPECTED_UV_LOCK_SHA256}"
        )
    markers = lock.get("resolution-markers", [])
    if EXPECTED_RESOLUTION_MARKER not in markers:
        raise VerificationError("exact Linux/Python 3.14 resolution marker is absent")
    return lock


TARGET_MARKER_ENVIRONMENT = {
    "implementation_name": "cpython",
    "implementation_version": "3.14.0",
    "os_name": "posix",
    "platform_machine": "x86_64",
    "platform_python_implementation": "CPython",
    "platform_release": "",
    "platform_system": "Linux",
    "platform_version": "",
    "python_full_version": "3.14.0",
    "python_version": "3.14",
    "sys_platform": "linux",
    "extra": "",
}


def marker_applies(value: object) -> bool:
    if value is None:
        return True
    if not isinstance(value, str):
        raise VerificationError("uv.lock contains a malformed environment marker")
    try:
        return Marker(value).evaluate(TARGET_MARKER_ENVIRONMENT)
    except InvalidMarker as error:
        raise VerificationError(f"uv.lock contains an invalid marker: {value!r}") from error


def dependency_extras(dependency: dict[str, object]) -> set[str]:
    raw_extras = dependency.get("extra", [])
    if not isinstance(raw_extras, list) or not all(
        isinstance(extra, str) and extra for extra in raw_extras
    ):
        raise VerificationError("uv.lock contains malformed dependency extras")
    return set(raw_extras)


def target_private_closure(
    lock: dict[str, object], externalized: tuple[str, ...]
) -> dict[str, str]:
    """Resolve the exact CPython 3.14/Linux root graph retained in the package."""
    raw_packages = lock.get("package", [])
    if not isinstance(raw_packages, list):
        raise VerificationError("uv.lock package inventory is malformed")

    root: dict[str, object] | None = None
    selected: dict[str, dict[str, object]] = {}
    for package in raw_packages:
        if not isinstance(package, dict) or not isinstance(package.get("name"), str):
            raise VerificationError("uv.lock contains malformed package metadata")
        name = canonical(package["name"])
        if name == "open-webui":
            if root is not None:
                raise VerificationError("uv.lock contains multiple Open WebUI roots")
            root = package
            continue

        raw_markers = package.get("resolution-markers", [])
        if not isinstance(raw_markers, list):
            raise VerificationError("uv.lock contains malformed resolution markers")
        if raw_markers and not any(marker_applies(marker) for marker in raw_markers):
            continue
        if name in selected:
            raise VerificationError(
                f"uv.lock selects multiple {name} distributions for the exact target"
            )
        selected[name] = package

    if root is None:
        raise VerificationError("uv.lock lacks the Open WebUI project root")

    optional_dependencies = root.get("optional-dependencies", {})
    if not isinstance(optional_dependencies, dict):
        raise VerificationError("Open WebUI optional dependency metadata is malformed")
    optional_all = optional_dependencies.get("all", [])
    if not isinstance(optional_all, list):
        raise VerificationError("Open WebUI all-extra metadata is malformed")
    qdrant_roots = [
        dependency
        for dependency in optional_all
        if isinstance(dependency, dict)
        and isinstance(dependency.get("name"), str)
        and canonical(dependency["name"]) == "qdrant-client"
    ]
    if len(qdrant_roots) != 1:
        raise VerificationError(
            "qdrant-client is not selected exactly once from the upstream optional graph"
        )

    excluded = set(externalized)
    requested_extras: defaultdict[str, set[str]] = defaultdict(set)
    processed_extras: dict[str, set[str]] = {}
    pending: deque[str] = deque()

    def enqueue(dependency: object) -> None:
        if not isinstance(dependency, dict) or not isinstance(
            dependency.get("name"), str
        ):
            raise VerificationError("uv.lock contains a malformed dependency edge")
        if not marker_applies(dependency.get("marker")):
            return
        name = canonical(dependency["name"])
        if name in excluded:
            return
        extras = dependency_extras(dependency)
        if name not in requested_extras or not extras.issubset(
            requested_extras[name]
        ):
            requested_extras[name].update(extras)
            pending.append(name)

    root_dependencies = root.get("dependencies", [])
    if not isinstance(root_dependencies, list):
        raise VerificationError("Open WebUI dependency metadata is malformed")
    for dependency in root_dependencies:
        enqueue(dependency)
    enqueue(qdrant_roots[0])

    while pending:
        name = pending.popleft()
        package = selected.get(name)
        if package is None:
            raise VerificationError(
                f"exact target closure references absent distribution {name}"
            )
        extras = requested_extras[name]
        if name in processed_extras and extras.issubset(processed_extras[name]):
            continue
        new_extras = extras.difference(processed_extras.get(name, set()))
        first_visit = name not in processed_extras
        processed_extras[name] = set(extras)

        if first_visit:
            dependencies = package.get("dependencies", [])
            if not isinstance(dependencies, list):
                raise VerificationError(
                    f"uv.lock contains malformed dependencies for {name}"
                )
            for dependency in dependencies:
                enqueue(dependency)

        optional = package.get("optional-dependencies", {})
        if not isinstance(optional, dict):
            raise VerificationError(
                f"uv.lock contains malformed optional dependencies for {name}"
            )
        for extra in new_extras:
            dependencies = optional.get(extra, [])
            if not isinstance(dependencies, list):
                raise VerificationError(
                    f"uv.lock contains malformed {name}[{extra}] dependencies"
                )
            for dependency in dependencies:
                enqueue(dependency)

    closure: dict[str, str] = {}
    for name in sorted(requested_extras):
        version = selected[name].get("version")
        if not isinstance(version, str) or not version:
            raise VerificationError(
                f"exact target distribution {name} has no locked version"
            )
        closure[name] = version
    return closure


def verify_exact_closure(
    expected: dict[str, str], constraints: dict[str, str]
) -> None:
    missing = sorted(set(expected).difference(constraints))
    extra = sorted(set(constraints).difference(expected))
    drifted = sorted(
        name
        for name in set(expected).intersection(constraints)
        if expected[name] != constraints[name]
    )
    if missing or extra or drifted:
        raise VerificationError(
            "private constraints differ from the exact target closure; "
            f"missing={missing}, extra={extra}, drifted={drifted}"
        )


def verify_upstream_binding(
    lock: dict[str, object],
    constraints: dict[str, str],
    externalized: tuple[str, ...] = EXPECTED_EXTERNALIZED,
) -> None:
    closure = target_private_closure(lock, externalized)
    verify_exact_closure(closure, constraints)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("uv_lock", type=Path)
    parser.add_argument("constraints", type=Path)
    parser.add_argument("system_providers", type=Path)
    parser.add_argument("requirements", type=Path)
    arguments = parser.parse_args()

    try:
        constraints = parse_constraints(arguments.constraints)
        providers = parse_name_list(arguments.system_providers, expected_count=21)
        if providers != EXPECTED_EXTERNALIZED:
            raise VerificationError("system-provider boundary differs from the audited set")
        overlap = sorted(set(constraints).intersection(providers))
        if overlap:
            raise VerificationError(
                f"private constraints contain system providers: {', '.join(overlap)}"
            )
        for name, version in EXPECTED_QDRANT_CLOSURE.items():
            if constraints.get(name) != version:
                raise VerificationError(
                    f"selected optional closure must contain {name}=={version}"
                )

        lock = parse_uv_lock(arguments.uv_lock)
        verify_upstream_binding(lock, constraints, providers)
        requirements = parse_hashed_requirements(arguments.requirements)
        if requirements != constraints:
            missing = sorted(set(constraints).difference(requirements))
            extra = sorted(set(requirements).difference(constraints))
            drifted = sorted(
                name
                for name in set(requirements).intersection(constraints)
                if requirements[name] != constraints[name]
            )
            raise VerificationError(
                "hashed requirements differ from constraints; "
                f"missing={missing}, extra={extra}, drifted={drifted}"
            )
    except VerificationError as error:
        print(f"verify-open-webui-private-lock: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
